# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: maven:3.3.3

pipelines:
  default:
    - step:
        script: # enable access to publish to maven repo
          - cat /etc/ssh/ssh_config
          - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
          - mkdir -p ~/.ssh
          - echo -e $EAWMVNKEY > ~/.ssh/eawmvn
          - chmod 0600 ~/.ssh/eawmvn
          - eval "$(ssh-agent)"
          - ssh-add ~/.ssh/eawmvn
          - ssh eawmvn@maven.edwardawebb.com 'whoami'  #validate SSH works before wasting time downloading internet
          - mvn --batch-mode --version
          - mvn --batch-mode clean install -DskipTests
          - mvn --batch-mode deploy -DskipTests