# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: maven:3.3.3

pipelines:
  default:
    - step:
        script: # enable access to publish to maven repo
          - mkdir -p ~/.ssh
          - echo -e $EAWMVNKEY > ~/.ssh/eawmvn
          - chmod 0600 ~/.ssh/eawmvn
          - wc -l ~/.ssh/eawmvn
          - wc -c ~/.ssh/eawmvn
          - eval "$(ssh-agent)"
          - ssh-add ~/.ssh/eawmvn
          - mvn --batch-mode --version
          - mvn --batch-mode clean install 
          - mvn --batch-mode deploy