# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: jamesdbloom/docker-java7-maven

pipelines:
  default:
    - step:
        script: # enable access to publish to maven repo
          - cat /etc/ssh/ssh_config
          - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
          - cat /etc/ssh/ssh_config
          - mkdir -p ~/.ssh
          - echo -e $EAWMVNKEY > ~/.ssh/id_rsa
          - chmod 0600 ~/.ssh/id_rsa
          - eval "$(ssh-agent)"
          - ssh-add ~/.ssh/id_rsa
          - ssh eawmvn@maven.edwardawebb.com "echo 2>&1" && echo $host SSH_OK || echo $host SSH_NOK  #validate SSH works before wasting time downloading internet
          - ping -c 10 maven.edwardawebb.com
          - ping -c 10 maven.atlassian.com
          - mvn --batch-mode --version
          - mvn --batch-mode deploy -DskipTests