# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: maven:3.3.3

pipelines:
  default:
    - step:
        script: # enable access to publish to maven repo
          - echo $EAWMVNKEY > ~/.ssh/eawmvn
          - chmod 0600 ~/.ssh/eawmvn
          - ssh-add ~/.ssh/eawmvn
    - step:
        script: # Modify the commands below to build your repository.
          - mvn --batch-mode --version
          - mvn --batch-mode clean install 
          - mvn --batch-mode deploy